name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'Kubernetes-Manifest/**'
      - 'VERSION'    
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}    
    - name: Build the Docker image
      run: |
        docker build --tag niketchandra/uptime:test-$(date +%s) .
        docker push niketchandra/uptime:test-$(date +%s)
    - name: Docker logout
      run: | 
        docker logout  
        
